mod relations;
mod types;

use crate::generators::{Generator, GeneratorConfig};
use crate::types::{NestedType, ObjectType, Schema, SchemaType};
use anyhow::Result;
use std::collections::HashMap;

use relations::{format_model_name, generate_field};

pub struct PrismaGenerator;

impl PrismaGenerator {
    pub fn new() -> Self {
        Self
    }

    fn generate_model(
        &self,
        name: &str,
        obj: &ObjectType,
        indent: &str,
        type_refs: &HashMap<String, String>,
        generate_relations: bool,
    ) -> String {
        let model_name = format_model_name(name);
        let mut lines = vec![format!("model {} {{", model_name)];

        lines.push(format!("{}id Int @id @default(autoincrement())", indent));

        for field in &obj.fields {
            if let Some(field_lines) = generate_field(field, indent, type_refs, generate_relations) {
                for line in field_lines {
                    lines.push(line);
                }
            }
        }

        lines.push("}".to_string());
        lines.join("\n")
    }

    fn build_type_refs(&self, nested_types: &[NestedType]) -> HashMap<String, String> {
        let mut refs = HashMap::new();
        for nt in nested_types {
            let key = format!("{:?}", nt.object);
            refs.insert(key, nt.name.clone());
        }
        refs
    }

    fn generate_nested_models(
        &self,
        nested_types: &[NestedType],
        indent: &str,
        type_refs: &HashMap<String, String>,
        generate_relations: bool,
    ) -> Vec<String> {
        nested_types
            .iter()
            .rev()
            .map(|nt| self.generate_model(&nt.name, &nt.object, indent, type_refs, generate_relations))
            .collect()
    }
}

impl Default for PrismaGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for PrismaGenerator {
    fn generate(&self, schema: &Schema, config: &GeneratorConfig) -> Result<String> {
        let mut output = vec!["// Generated by mold".to_string(), String::new()];

        let type_refs = if config.flat_mode {
            HashMap::new()
        } else {
            self.build_type_refs(&schema.nested_types)
        };

        if !config.flat_mode && !schema.nested_types.is_empty() {
            let nested = self.generate_nested_models(
                &schema.nested_types,
                &config.indent,
                &type_refs,
                config.prisma_generate_relations,
            );
            for model in nested {
                output.push(model);
                output.push(String::new());
            }
        }

        if let SchemaType::Object(obj) = &schema.root_type {
            output.push(self.generate_model(
                &schema.name,
                obj,
                &config.indent,
                &type_refs,
                config.prisma_generate_relations,
            ));
        }

        Ok(output.join("\n"))
    }

    fn file_extension(&self) -> &'static str {
        "prisma"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::Field;

    #[test]
    fn test_generate_simple_model() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![
            Field::new("name", SchemaType::String),
            Field::new("age", SchemaType::Integer),
            Field::new("active", SchemaType::Boolean),
        ]);
        let schema = Schema::new("User", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("model User {"));
        assert!(output.contains("id Int @id @default(autoincrement())"));
        assert!(output.contains("name String"));
        assert!(output.contains("age Int"));
        assert!(output.contains("active Boolean"));
    }

    #[test]
    fn test_generate_array_field() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![Field::new(
            "tags",
            SchemaType::Array(Box::new(SchemaType::String)),
        )]);
        let schema = Schema::new("Post", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("tags String[]"));
    }

    #[test]
    fn test_generate_float_field() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![Field::new("price", SchemaType::Number)]);
        let schema = Schema::new("Product", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("price Float"));
    }

    #[test]
    fn test_reserved_word_handling() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![Field::new("model", SchemaType::String)]);
        let schema = Schema::new("Test", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("model_ String"));
    }

    #[test]
    fn test_datetime_field() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![Field::new("createdAt", SchemaType::DateTime)]);
        let schema = Schema::new("Post", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("createdAt DateTime"));
        assert!(output.contains("@default(now())"));
    }

    #[test]
    fn test_updated_at_field() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![Field::new("updatedAt", SchemaType::DateTime)]);
        let schema = Schema::new("Post", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("updatedAt DateTime"));
        assert!(output.contains("@updatedAt"));
    }

    #[test]
    fn test_uuid_id_field_gets_default() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![Field::new("id", SchemaType::Uuid)]);
        let schema = Schema::new("User", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        // The field named "id" with Uuid type should get @default(uuid())
        assert!(output.contains("@default(uuid())"));
    }

    #[test]
    fn test_optional_prisma_field() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![
            Field::new("name", SchemaType::String),
            Field::new("bio", SchemaType::String).optional(),
        ]);
        let schema = Schema::new("User", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("name String"));
        assert!(output.contains("bio String?"));
    }

    #[test]
    fn test_nested_model_generation() {
        let gen = PrismaGenerator::new();
        let address_obj = ObjectType::new(vec![
            Field::new("street", SchemaType::String),
            Field::new("city", SchemaType::String),
        ]);
        let root_obj = ObjectType::new(vec![
            Field::new("name", SchemaType::String),
            Field::new("address", SchemaType::Object(address_obj.clone())),
        ]);
        let schema = Schema::new("User", SchemaType::Object(root_obj))
            .with_nested_types(vec![NestedType::new("UserAddress", address_obj)]);
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("model UserAddress {"));
        assert!(output.contains("model User {"));
    }

    #[test]
    fn test_boolean_array_field() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![Field::new(
            "flags",
            SchemaType::Array(Box::new(SchemaType::Boolean)),
        )]);
        let schema = Schema::new("Test", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("flags Boolean[]"));
    }

    #[test]
    fn test_file_extension() {
        let gen = PrismaGenerator::new();
        assert_eq!(gen.file_extension(), "prisma");
    }

    #[test]
    fn test_always_has_autoincrement_id() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![Field::new("name", SchemaType::String)]);
        let schema = Schema::new("Test", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("id Int @id @default(autoincrement())"));
    }

    #[test]
    fn test_pascal_case_model_name() {
        let gen = PrismaGenerator::new();
        let obj = ObjectType::new(vec![Field::new("name", SchemaType::String)]);
        // "model" gets PascalCased to "Model" by format_model_name
        let schema = Schema::new("model", SchemaType::Object(obj));
        let config = GeneratorConfig::default();

        let output = gen.generate(&schema, &config).unwrap();

        assert!(output.contains("model Model {"));
    }
}
